# Generated by Django 2.1.7 on 2020-06-08 11:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DictBrand',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='nazwa', max_length=200, null=True)),
                ('is_active', models.IntegerField(blank=True, db_column='aktywny', null=True)),
                ('is_system', models.IntegerField(blank=True, db_column='systemowy', null=True)),
            ],
            options={
                'db_table': 'slownik_marki',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DictCategory',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='nazwa', max_length=200, null=True)),
                ('is_active', models.IntegerField(blank=True, db_column='aktywny', null=True)),
                ('is_system', models.IntegerField(blank=True, db_column='systemowy', null=True)),
            ],
            options={
                'db_table': 'slownik_kategorie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DictGroup',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='nazwa', max_length=200, null=True)),
                ('name_autopanel', models.CharField(blank=True, db_column='nazwa_autopanel', max_length=50, null=True)),
                ('identificator', models.CharField(blank=True, db_column='identyfikator', max_length=9, null=True)),
                ('id_worker_1', models.IntegerField(blank=True, db_column='id_pracownika_1', null=True)),
                ('id_worker_2', models.IntegerField(blank=True, db_column='id_pracownika_2', null=True)),
                ('is_active', models.IntegerField(blank=True, db_column='aktywny', null=True)),
                ('is_system', models.IntegerField(blank=True, db_column='systemowy', null=True)),
            ],
            options={
                'db_table': 'slownik_grupy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DictModel',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='nazwa', max_length=200, null=True)),
                ('is_active', models.IntegerField(blank=True, db_column='aktywny', null=True)),
                ('is_system', models.IntegerField(blank=True, db_column='systemowy', null=True)),
            ],
            options={
                'db_table': 'slownik_modele',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DictTrailerType',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='nazwa', max_length=200, null=True)),
                ('is_active', models.IntegerField(blank=True, db_column='aktywny', null=True)),
                ('is_system', models.IntegerField(blank=True, db_column='systemowy', null=True)),
            ],
            options={
                'db_table': 'slownik_typy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DictType',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='nazwa', max_length=200, null=True)),
                ('is_active', models.IntegerField(blank=True, db_column='aktywny', null=True)),
                ('is_system', models.IntegerField(blank=True, db_column='systemowy', null=True)),
            ],
            options={
                'db_table': 'slownik_rodzaje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DictTypeOfFuel',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='nazwa', max_length=200, null=True)),
                ('is_active', models.IntegerField(blank=True, db_column='aktywny', null=True)),
                ('is_system', models.IntegerField(blank=True, db_column='systemowy', null=True)),
            ],
            options={
                'db_table': 'slownik_rodzaje_paliwa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('is_active', models.IntegerField(blank=True, db_column='aktywny', null=True)),
                ('is_auction', models.IntegerField(blank=True, db_column='aukcja', null=True)),
                ('price', models.DecimalField(blank=True, db_column='cena', decimal_places=2, max_digits=10, null=True)),
                ('identificator', models.CharField(blank=True, db_column='identyfikator', max_length=12, null=True)),
                ('name', models.CharField(blank=True, db_column='nazwa', max_length=200, null=True)),
                ('description', models.TextField(blank=True, db_column='opis', null=True)),
                ('date_updates', models.DateTimeField(blank=True, db_column='ostatnia_modyfikacja', null=True)),
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('promotion', models.IntegerField(blank=True, db_column='promocja', null=True)),
                ('year_production', models.IntegerField(blank=True, db_column='rok_produkcji', null=True)),
                ('is_sold', models.IntegerField(blank=True, db_column='sprzedany', null=True)),
                ('slug', models.SlugField(db_column='slug')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
                'db_table': 'maszyny',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, db_column='start_date')),
                ('ordered_date', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supercar.Item')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.ManyToManyField(to='supercar.OrderItem'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
