# Generated by Django 2.1.7 on 2020-06-11 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DictBrand',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='nazwa', max_length=200, null=True)),
                ('is_active', models.IntegerField(blank=True, db_column='aktywny', null=True)),
                ('is_system', models.IntegerField(blank=True, db_column='systemowy', null=True)),
            ],
            options={
                'db_table': 'slownik_marki',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DictCategory',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='nazwa', max_length=200, null=True)),
                ('is_active', models.IntegerField(blank=True, db_column='aktywny', null=True)),
                ('is_system', models.IntegerField(blank=True, db_column='systemowy', null=True)),
            ],
            options={
                'db_table': 'slownik_kategorie',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DictGroup',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='nazwa', max_length=200, null=True)),
                ('name_autopanel', models.CharField(blank=True, db_column='nazwa_autopanel', max_length=50, null=True)),
                ('identificator', models.CharField(blank=True, db_column='identyfikator', max_length=9, null=True)),
                ('id_worker_1', models.IntegerField(blank=True, db_column='id_pracownika_1', null=True)),
                ('id_worker_2', models.IntegerField(blank=True, db_column='id_pracownika_2', null=True)),
                ('is_active', models.IntegerField(blank=True, db_column='aktywny', null=True)),
                ('is_system', models.IntegerField(blank=True, db_column='systemowy', null=True)),
            ],
            options={
                'db_table': 'slownik_grupy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DictModel',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='nazwa', max_length=200, null=True)),
                ('is_active', models.IntegerField(blank=True, db_column='aktywny', null=True)),
                ('is_system', models.IntegerField(blank=True, db_column='systemowy', null=True)),
            ],
            options={
                'db_table': 'slownik_modele',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DictTrailerType',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='nazwa', max_length=200, null=True)),
                ('is_active', models.IntegerField(blank=True, db_column='aktywny', null=True)),
                ('is_system', models.IntegerField(blank=True, db_column='systemowy', null=True)),
            ],
            options={
                'db_table': 'slownik_typy',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DictType',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='nazwa', max_length=200, null=True)),
                ('is_active', models.IntegerField(blank=True, db_column='aktywny', null=True)),
                ('is_system', models.IntegerField(blank=True, db_column='systemowy', null=True)),
            ],
            options={
                'db_table': 'slownik_rodzaje',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DictTypeOfFuel',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='nazwa', max_length=200, null=True)),
                ('is_active', models.IntegerField(blank=True, db_column='aktywny', null=True)),
                ('is_system', models.IntegerField(blank=True, db_column='systemowy', null=True)),
            ],
            options={
                'db_table': 'slownik_rodzaje_paliwa',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('is_active', models.IntegerField(blank=True, db_column='aktywny', null=True)),
                ('is_auction', models.IntegerField(blank=True, db_column='aukcja', null=True)),
                ('price', models.DecimalField(blank=True, db_column='cena', decimal_places=2, max_digits=10, null=True)),
                ('identificator', models.CharField(blank=True, db_column='identyfikator', max_length=12, null=True)),
                ('name', models.CharField(blank=True, db_column='nazwa', max_length=200, null=True)),
                ('description', models.TextField(blank=True, db_column='opis', null=True)),
                ('date_updates', models.DateTimeField(blank=True, db_column='ostatnia_modyfikacja', null=True)),
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('promotion', models.IntegerField(blank=True, db_column='promocja', null=True)),
                ('year_production', models.IntegerField(blank=True, db_column='rok_produkcji', null=True)),
                ('is_sold', models.IntegerField(blank=True, db_column='sprzedany', null=True)),
                ('slug', models.SlugField(db_column='slug')),
                ('discount_price', models.FloatField(db_column='discount_price')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
                'db_table': 'maszyny',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street_address', models.CharField(max_length=100)),
                ('apartment_address', models.CharField(max_length=100)),
                ('zip', models.CharField(max_length=100)),
                ('address_type', models.CharField(choices=[('B', 'Billing'), ('S', 'Shipping')], max_length=1)),
                ('default', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Addresses',
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=15)),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, db_column='start_date')),
                ('ordered_date', models.DateTimeField()),
                ('ordered', models.BooleanField(default=False)),
                ('being_delivered', models.BooleanField(default=False)),
                ('received', models.BooleanField(default=False)),
                ('refund_requested', models.BooleanField(default=False)),
                ('refund_granted', models.BooleanField(default=False)),
                ('billing_address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='billing_address', to='supercar.Address')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supercar.Coupon')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('ordered', models.BooleanField(default=False)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supercar.Item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_charge_id', models.CharField(max_length=50)),
                ('amount', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('accepted', models.BooleanField(default=False)),
                ('email', models.EmailField(max_length=254)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supercar.Order')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_customer_id', models.CharField(blank=True, max_length=50, null=True)),
                ('one_click_purchasing', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='item',
            field=models.ManyToManyField(to='supercar.OrderItem'),
        ),
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='supercar.Payment'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shipping_address', to='supercar.Address'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
